---
name: Setup Ansible
description: Install Ansible and its dependencies
inputs:
  version:
    default: 11.2.0
    description: The version of Ansible to install
    required: true

runs:
  using: composite
  steps:
  - name: Install Python packages
    shell: sh
    run: |
      pip3 install \
        ansible==${{ inputs.version }} \
        google-cloud-secret-manager==2.23.0
