---
name: Setup SSH client
inputs:
  ssh_private_key:
    required: true

runs:
  using: composite
  steps:
  - name: Run ssh-agent
    shell: sh
    env:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
    run: |
      mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh
      cat > $HOME/.ssh/known_hosts <<EOF
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      EOF
      eval $(ssh-agent -s -a $SSH_AUTH_SOCK)
      echo '${{ inputs.ssh_private_key }}' | tr -d '\r' | ssh-add -
      echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
